---
- name: Upgrade OS
  apt: upgrade=dist

- name: install certbot
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /home/{{user_name}}/certbot-auto
    mode: "a+x"

- name: See if certification already exists
  stat: path=/etc/letsencrypt/live/{{domain}}
  register: cert_exist

- name: See if server folder already exists
  stat: path={{server_path}}
  register: server_exist

- name: Run Certification Inside Apache
  command: /home/{{user_name}}/certbot-auto certonly -n --webroot -w {{server_path}} -d {{domain}} -d {{www_domain}} --email {{admin_email}} --agree-tos
  become: yes
  become_method: sudo
  when: (cert_exist.stat.isdir is not defined or cert_exist.stat.isdir == false) and (cert_exist.stat.isdir is defined and cert_exist.stat.isdir)

- name: Run Certification Standalone
  command: /home/{{user_name}}/certbot-auto certonly -n --standalone -d {{domain}} -d {{www_domain}} --email {{admin_email}} --agree-tos
  become: yes
  become_method: sudo
  when: (cert_exist.stat.isdir is not defined or cert_exist.stat.isdir == false) and (cert_exist.stat.isdir is not defined or cert_exist.stat.isdir == false)

- name: Change ownership of letsencrypt folder
  file: path=/etc/letsencrypt owner={{user_name}} group={{user_name}} state=directory mode=0755 recurse=yes
  become: yes
  become_method: sudo

- name: Renew Certification Cron Job
  cron: name="renew cert" day=1 month="*/2" minute=0 hour=0
        user="root" job="/home/{{user_name}}/certbot-auto renew --quiet --no-self-upgrade"
